cron: 0/10 * * * * ? 
mybatis: 
    mapper-locations: classpath:template/*.xml
    typeAliasesPackage: cn.com.entity

spring: 
    datasource: 
        url: jdbc:mysql://192.168.16.239:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    mvc: 
       view: 
           prefix: /WEB-INF/jsp/
           suffix: .jsp
