cron: 0 0 * * * ? 
mybatis: 
    mapper-locations: classpath:template/*.xml
    typeAliasesPackage: cn.com.entity
    config-location: classpath:mybatis-config.xml
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/presale?autoReconnect=true&useUnicode=yes&amp;characterEncoding=UTF8&allowMultiQueries=true&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    mvc: 
       view: 
           prefix: /WEB-INF/jsp/
           suffix: .jsp
logging: 
    level: 
        cn.com.dao: debug
